# Site settings
name: Ahsan Nadeem

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/anadeem49
 - title: LinkedIn
   url: https://www.linkedin.com/in/ahsan-nadeem

#Any buzzword skills you want to include
skills:
 - Java
 - Javascript
 - HTML
 - CSS
 - C++

#Work experience is required
roles:
 - title: Computer Science Tutor
   start: October 2019
   end: Ongoing
   employer: CUNY Research Foundation
   description: Currently tutor groups of at least 3 high school students in computer science via one-on-one sessions 
                or small groups
                
 - title: IT Services Intern
   start: June 2019
   end: September 2019
   employer: NY Presbyterian Hospital
   description: Tested the compatibility of at least 2 CPUs and monitors
                Imaged at least 4 WYSE machines
   
 - title: Computer Lab Technician
   start: November 2018
   end: May 2019
   employer: CUNY Brooklyn College
   description: Assigned 3 students to computers per minute
                Answered 2 phone calls a minute related to lab inquiry
                Helped troubleshoot computers, scanners, and printers under technical supervision
   
 - title: Assistant Secretary of Engineering Club
   start: June 2018
   end: May 2019
   employer: CUNY Brooklyn College
   description: Helped promote and innovate the use of math and science in engineering by inviting 2 professional engineers 
                every month to talk about their careers and give advice to 30+ students on career paths


#Education is required
education:
 - level: Bachelor of Science (BS)
   date: 2017 - 2021
   subject: Computer Science
   school: CUNY Brooklyn College

#This section is optional (as is the image link below)
Udemy:
   courses:
    - title: Data Structures and Algorithms - The Complete Masterclass
      link: https://www.udemy.com/course/data-structures-and-algorithms-the-complete-guide/
      date: August 18, 2019

Intro:
     I am an undergraduate student at CUNY Brooklyn College pursuing a Bachelors of Science in Computer Science. My areas of
     expertise involve Java, with working knowldge of HTML, CSS and Javascript and learning C++. My current role involves 
     tutoring high school students in computer science, where I work with 2 or 3 students at a time to address their issues 
     with their code.
